### ISSUE TITLE
SecretID is hardcoded in readme file

### ISSUE THREAD

**Issue by tylerezimmerman** [DelineaXPM/terraform-provider-dsv#21]
**Description of the issue**

SecretID is hardcoded in readme file

**Expected behavior**

Secret should be fetched from vault or other secure method

**Actual behavior**

Credential is hardcoded. 

**Steps to reproduce**

![image](https://user-images.githubusercontent.com/100804646/191779715-a83d6e99-5342-4510-8697-b00311011a89.png)

**Comment by sheldonhull** [comment]
tfvars are typically not included in github commits, but yes, maybe a better example could be provided for alternative approaches. Since this also can change based on the Terraform cloud secure variables or the provider I'll think on how to provide some examples here. thanks for bringing this up.
