### ISSUE TITLE
have ability to download provider without going via Terraform Registry

### ISSUE THREAD

**Issue by BAu0002** [DelineaXPM/terraform-provider-dsv#80]
Can we have the Terraform Provider package downloadable via Git so it can be download and installed in an offline docker container.

**Comment by sheldonhull** [comment]
This already publishes to the github releases as well as registry so you should be able to download whatever asset you want and copy into a docker container. Look at github releases section. Cheers!

**Comment by BAu0002** [comment]
doh, how did I miss that.
